project:
  name: "Full SDLC Team"
  orchestrator: "./orchestrator/orchestrator_runner.py"
  agent_folder: "./agents"
  output_folder: "./outputs"
  execution_order:
    - 01_product_owner.md
    - 02_analyst.md
    - 03_designer.md
    - 04_developer.md
    - 05_QA.md
    - 06_DevOps.md